whi_qrcode_pose:
  frame_id: camera
  image_topic: /whi_3dobject_tracking/color_view
  camera_device: /dev/video0
  image_path: image
  source: path # topic/device/path
  loop_hz: 20 # hz
  show_source_image: true
  show_detected_image: true
  service: offset_request
  intrinsic_projection: [385.75, 385.75, 323.12, 236.74] #[969.751, 969.751, 977.493, 522.116]
  intrinsic_distortion: [0.0, 0.0, 0.0, 0.0]
