whi_qrcode_pose:
  frame_id: camera
  source: device # topic/device/path
  topic:
    img_topic: /whi_pgnd_inspection/color_view #/camera/color/image_raw
  device:
    cam_device: /dev/video0
  path:
    img_path: debug_images
  loop_hz: 20 # hz
  show_source_image: true
  show_detected_image: true
  activated_default: true
  frame_unit: meter # millimeter
  intrinsic_projection: [592.23959, 592.54237, 320.05740, 263.84056] # focal length x, y, and optical center x, y
  intrinsic_distortion: [1.813679e-03, 9.554750e-01, 1.242037e-03, 2.211452e-03, -3.219694e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00]
  type: aruco # qr or aruco
  # ArUco
  aruco:
    dictionary: DICT_4X4_50
    marker_side_length: 0.165 # in meter
    min_marker_perimeter: 100 # in pixel
