whi_qrcode_pose:
  frame_id: camera
  source: device # topic/device/path
  topic:
    img_topic: /whi_pgnd_inspection/color_view
  device:
    cam_device: /dev/video0
  path:
    img_path: debug_images
  loop_hz: 20 # hz
  show_source_image: true
  show_detected_image: true
  activated_default: true
  frame_unit: meter # millimeter
  intrinsic_projection: [386.157, 386.157, 323.237, 239.697] # focal length x, y, and optical center x, y
  intrinsic_distortion: [0.0, 0.0, 0.0, 0.0]
  type: aruco # qr or aruco
  # ArUco
  aruco:
    dictionary: DICT_4X4_50
    marker_side_length: 0.165 # in meter
    min_marker_perimeter: 100 # in pixel
