whi_qrcode_pose:
  frame_id: camera
  image_topic: /camera/color/image_raw
  camera_device: /dev/video0
  image_path: debug_images
  source: topic # topic/device/path
  loop_hz: 20 # hz
  show_source_image: false
  show_detected_image: true
  service: qrcode_pose
  frame_unit: meter # millimeter
  intrinsic_projection: [386.522, 386.522, 324.621, 235.764] # focal length x, y, and optical center x, y
  intrinsic_distortion: [0.0, 0.0, 0.0, 0.0]
