whi_qrcode_pose:
  frame_id: camera
  image_topic: /whi_pgnd_inspection/color_view
  camera_device: /dev/video0
  image_path: debug_images
  source: topic # topic/device/path
  loop_hz: 20 # hz
  show_source_image: false
  show_detected_image: false
  activated_default: false
  frame_unit: meter # millimeter
  intrinsic_projection: [386.157, 386.157, 323.237, 239.697] # focal length x, y, and optical center x, y
  intrinsic_distortion: [0.0, 0.0, 0.0, 0.0]
